spring:
  profiles:
    active:
      - dog
      - EN
      - dev
guru:
  username: superuser
  password: supersecretpassword
  jdbcurl: someURLpropertiesYML

---
spring:
  profiles: prod
guru:
  username: PRODsuperuser
  password: PRODsupersecretpassword
  jdbcurl: PRODsomeURLpropertiesYML
